//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.27 at 09:29:49 AM PDT 
//


package com.photolude.mob.plugins.commons.ppl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.photolude.plugins.commons.ppl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.photolude.plugins.commons.ppl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Ppl }
     * 
     */
    public Ppl createPpl() {
        return new Ppl();
    }

    /**
     * Create an instance of {@link PluginType }
     * 
     */
    public PluginType createPluginType() {
        return new PluginType();
    }

    /**
     * Create an instance of {@link PageDefinitionType }
     * 
     */
    public PageDefinitionType createPageDefinitionType() {
        return new PageDefinitionType();
    }

    /**
     * Create an instance of {@link ResourceList }
     * 
     */
    public ResourceList createResourceList() {
        return new ResourceList();
    }

    /**
     * Create an instance of {@link MainMenuItemType }
     * 
     */
    public MainMenuItemType createMainMenuItemType() {
        return new MainMenuItemType();
    }

    /**
     * Create an instance of {@link MainMenuType }
     * 
     */
    public MainMenuType createMainMenuType() {
        return new MainMenuType();
    }

}
